### ISSUE TITLE
Build fails under Manjaro

### ISSUE THREAD

**Issue by maxigaz** [odrevet/gjiten-kai#1] opened 2021-03-23 13:49 UTC
I’ve just tried installing the AUR package `gjitenkai-git` on Manjaro Linux x86-64. The build process fails with the following ouput (I'm posting the last part before the error):

```
[100%] Linking C executable bin/gjitenkai
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/gjitenkai.c.o:(.bss+0x0): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/gjitenkai.c.o:(.bss+0x8): multiple definition of `download_location'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x10): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/gjitenkai.c.o:(.bss+0x10): multiple definition of `session'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x18): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/gjitenkai.c.o:(.bss+0x18): multiple definition of `cursor_default'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x20): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/gjitenkai.c.o:(.bss+0x20): multiple definition of `cursor_selection'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x28): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/callbacks.c.o:(.bss+0x0): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/callbacks.c.o:(.bss+0x8): multiple definition of `download_location'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x10): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/callbacks.c.o:(.bss+0x10): multiple definition of `session'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x18): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/callbacks.c.o:(.bss+0x18): multiple definition of `cursor_default'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x20): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/gjitenkai/callbacks.c.o:(.bss+0x20): multiple definition of `cursor_selection'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x28): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/conf.c.o:(.bss+0x0): multiple definition of `download_location'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x10): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/conf.c.o:(.bss+0x8): multiple definition of `session'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x18): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/conf.c.o:(.bss+0x10): multiple definition of `cursor_default'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x20): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/conf.c.o:(.bss+0x18): multiple definition of `cursor_selection'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x28): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/worddic.c.o:(.bss+0x18): multiple definition of `cursor_selection'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x28): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/worddic.c.o:(.bss+0x10): multiple definition of `cursor_default'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x20): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/worddic.c.o:(.bss+0x0): multiple definition of `download_location'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x10): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/worddic.c.o:(.bss+0x8): multiple definition of `session'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x18): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/preferences.c.o:(.bss+0x8): multiple definition of `download_location'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x10): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/preferences.c.o:(.bss+0x10): multiple definition of `session'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x18): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/preferences.c.o:(.bss+0x18): multiple definition of `cursor_default'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x20): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/preferences.c.o:(.bss+0x20): multiple definition of `cursor_selection'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x28): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/callbacks.c.o:(.bss+0x0): multiple definition of `download_location'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x10): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/callbacks.c.o:(.bss+0x18): multiple definition of `cursor_selection'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x28): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/callbacks.c.o:(.bss+0x10): multiple definition of `cursor_default'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x20): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/worddic/callbacks.c.o:(.bss+0x8): multiple definition of `session'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x18): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/kanjidic/conf.c.o:(.bss+0x0): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/kanjidic/kanjidic.c.o:(.bss+0x8): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/kanjidic/callbacks.c.o:(.bss+0x8): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/kanjidic/radical_window.c.o:(.bss+0x0): multiple definition of `button_list'; CMakeFiles/gjitenkai.dir/src/kanjidic/callbacks.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/kanjidic/radical_window.c.o:(.bss+0x8): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/kanjidic/preferences.c.o:(.bss+0x0): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
/usr/bin/ld: CMakeFiles/gjitenkai.dir/src/kanjidic/kanji_item.c.o:(.bss+0x0): multiple definition of `kanji_item_list'; CMakeFiles/gjitenkai.dir/src/gjitenkai/main.c.o:(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gjitenkai.dir/build.make:493: bin/gjitenkai] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/gjitenkai.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: Unable to build gjitenkai-git - makepkg exited with code: 4
```

**Comment by odrevet** [comment] 2021-03-29 19:12
I can reproduce the issue under docker (issue do not appear under ubuntu). 
For future reference: 

```
docker run -it --rm -v ${PWD}:/home/user/gjiten-kai manjarosway/base bash
sudo pacman-mirrors --country all --api --protocols all --set-branch stable && sudo pacman -Syyu
pacman -S gtk3
cd home/user/gjiten-kai/
cmake .
make
```

This issue is probably introduced by the new version of cmake, as I build with the same gcc and make version under ubuntu

Manjaro 
```
[root@b17bf47b7d59 gjiten-kai]# gcc --version
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@b17bf47b7d59 gjiten-kai]# cmake --version
cmake version 3.19.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@b17bf47b7d59 gjiten-kai]# make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Ubuntu
```
olivier@odpc:~$ gcc --version
gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

olivier@odpc:~$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
olivier@odpc:~$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
olivier@odpc:~$ 
```

now to fix this using the dockerized manjaro

**Comment by odrevet** [comment] 2021-03-29 20:06
Turns out GCC 10 is more strict on global variables
https://gcc.gnu.org/gcc-10/porting_to.html

I added the -fcommon as a temporary fix, until that global variables are properly declare using extern

**Comment by odrevet** [comment] 2021-03-29 20:45
Globals are now declared using extern and the software can be build under manjaro and probably other distro
The download from preference and kanji details do not work anymore. 
I am closing the issue although new bugs are related to this issue they will be fix in a separate issue

EDIT: this is more complicated that I thougth. move fix that break kanji details and download into it's own branch and revert it from master

**Closed as completed by odrevet** 2021-03-29 20:45 UTC
